/**
 * Cast an award vote. Public.
 *
 *   POST -> { awardId, nomineeId, voterIdentifier, voterName? }
 *
 * This is the only write the public can make, and it still goes through the
 * server so the rules are actually enforced: the award must exist, be active
 * and be inside its voting window, and the nominee must belong to that award.
 * The database's UNIQUE(award_id, voter_identifier) constraint is what really
 * prevents double voting -- a check-then-insert in the browser could always be
 * raced or skipped.
 *
 * Note: voterIdentifier is generated by the browser, so a determined voter can
 * still clear it and vote again. That was true before as well. If ballot
 * integrity starts to matter, tie voting to a real login instead.
 */

import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabaseAdmin'
import { fail, readJson } from '@/lib/apiAuth'

interface VoteBody {
  awardId?: string
  nomineeId?: string
  voterIdentifier?: string
  voterName?: string
}

export async function POST(request: Request) {
  const body = await readJson<VoteBody>(request)
  if (!body) return fail('Invalid request body')

  const { awardId, nomineeId, voterIdentifier } = body
  if (!awardId) return fail('awardId is required')
  if (!nomineeId) return fail('nomineeId is required')
  if (!voterIdentifier) return fail('voterIdentifier is required')

  const { data: award, error: awardError } = await supabaseAdmin
    .from('awards')
    .select('id, is_active, voting_start_date, voting_end_date')
    .eq('id', awardId)
    .maybeSingle()

  if (awardError) {
    console.error('Error loading award:', awardError)
    return fail('Failed to load award', 500)
  }
  if (!award) return fail('Award not found', 404)
  if (!award.is_active) return fail('Voting for this award is closed', 403)

  const now = Date.now()
  if (award.voting_start_date && now < Date.parse(award.voting_start_date)) {
    return fail('Voting for this award has not opened yet', 403)
  }
  if (award.voting_end_date && now > Date.parse(award.voting_end_date)) {
    return fail('Voting for this award has closed', 403)
  }

  // The nominee must belong to the award being voted on.
  const { data: nominee, error: nomineeError } = await supabaseAdmin
    .from('award_nominees')
    .select('id, award_id')
    .eq('id', nomineeId)
    .maybeSingle()

  if (nomineeError) {
    console.error('Error loading nominee:', nomineeError)
    return fail('Failed to load nominee', 500)
  }
  if (!nominee || nominee.award_id !== awardId) {
    return fail('That nominee is not up for this award', 400)
  }

  const { error: insertError } = await supabaseAdmin.from('award_votes').insert({
    award_id: awardId,
    nominee_id: nomineeId,
    voter_identifier: voterIdentifier,
    voter_name: body.voterName?.trim() || null,
  })

  if (insertError) {
    if (insertError.code === '23505') {
      return fail('You have already voted for this award', 409)
    }
    console.error('Error recording vote:', insertError)
    return fail('Failed to record vote', 500)
  }

  return NextResponse.json({ success: true }, { status: 201 })
}
