#!/usr/bin/env python3
"""
Wrap an SVG logo in a filled circle.

Some crests are drawn to sit on a dark shirt and are a single pale or flat
colour. Rendered on the site, which draws crests on white, they wash out --
the Kabul gold is 2.44:1, under the 3:1 a graphical object needs. Recolouring
would change the artwork; putting it on a disc of the club's own colour keeps
the mark exactly as drawn and gives it something to read against.

Nothing currently ships through this script -- see the contrast note in
public/images/teams/README.md for which crests are candidates and why they
were left alone.

The source is nested inside the output rather than edited, so re-running this
after a fresh export from Illustrator cannot drift from the original artwork.
Output stays vector, so it is resolution-independent like any other crest.

    python3 scripts/disc-backdrop.py in.svg out.svg --color '#4F8A8A'

    --color   disc fill, #RRGGBB (required)
    --inset   how much of the diameter the mark spans, 0-1 (default 0.62)

Reports the WCAG contrast ratio between each fill in the artwork and the disc,
because the whole point is that the mark can be seen: under 3:1 fails for a
graphical object and wants a deeper --color.

Pure standard library, so it runs anywhere without installing anything.
"""

import argparse
import re
import sys

NAMED = {"white": (255, 255, 255), "black": (0, 0, 0), "none": None}


def parse_colour(text):
    text = text.strip().lower()
    if text in NAMED:
        return NAMED[text]
    if not text.startswith("#"):
        return None  # url(#gradient), currentColor, and friends: not a flat fill
    digits = text[1:]
    if len(digits) == 3:
        digits = "".join(c * 2 for c in digits)
    if len(digits) != 6:
        return None
    try:
        return tuple(int(digits[i : i + 2], 16) for i in (0, 2, 4))
    except ValueError:
        return None


def colour_arg(text):
    rgb = parse_colour(text)
    if rgb is None:
        raise argparse.ArgumentTypeError("colour must be #RGB or #RRGGBB")
    return rgb


def relative_luminance(rgb):
    channels = []
    for value in rgb:
        c = value / 255.0
        channels.append(c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4)
    r, g, b = channels
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast_ratio(a, b):
    la, lb = relative_luminance(a), relative_luminance(b)
    return (max(la, lb) + 0.05) / (min(la, lb) + 0.05)


def fills(svg):
    """Every flat colour the artwork paints with, in document order."""
    found = []
    for match in re.finditer(r'fill\s*[:=]\s*"?\s*([^;"\s>}]+)', svg):
        rgb = parse_colour(match.group(1))
        if rgb is not None and rgb not in found:
            found.append(rgb)
    return found


def split_root(svg):
    """Returns (viewBox, inner markup) for the outermost <svg> element."""
    match = re.search(r"<svg\b([^>]*)>", svg, re.IGNORECASE)
    if not match:
        sys.exit("no <svg> element found")

    view_box = re.search(r'viewBox\s*=\s*"([^"]+)"', match.group(1), re.IGNORECASE)
    if not view_box:
        sys.exit(
            "the source <svg> has no viewBox, so it cannot be scaled into the "
            "disc. Re-export with one."
        )

    end = svg.rindex("</svg>")
    return view_box.group(1), svg[match.end() : end]


def main():
    parser = argparse.ArgumentParser(description="Wrap an SVG logo in a filled circle.")
    parser.add_argument("source")
    parser.add_argument("destination")
    parser.add_argument("--color", "--colour", dest="color", type=colour_arg,
                        required=True, help="disc fill, #RRGGBB")
    parser.add_argument("--inset", type=float, default=0.62,
                        help="fraction of the diameter the mark spans (0-1)")
    args = parser.parse_args()

    if not 0 < args.inset <= 1:
        parser.error("--inset must be between 0 and 1")

    with open(args.source, encoding="utf-8") as handle:
        source = handle.read()

    view_box, inner = split_root(source)
    span = round(100 * args.inset, 4)
    offset = round((100 - span) / 2, 4)
    disc = "#%02x%02x%02x" % args.color

    # The mark is nested as a child <svg> with its own viewBox: the default
    # preserveAspectRatio then fits it inside the box and centres it, so a
    # non-square mark keeps its proportions without any arithmetic here.
    out = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f"<!-- Generated by scripts/disc-backdrop.py from {args.source}. Do not\n"
        "     edit: re-run the command in public/images/teams/README.md. -->\n"
        '<svg xmlns="http://www.w3.org/2000/svg" '
        'xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100">\n'
        f'  <circle cx="50" cy="50" r="50" fill="{disc}"/>\n'
        f'  <svg x="{offset}" y="{offset}" width="{span}" height="{span}" '
        f'viewBox="{view_box}">{inner}</svg>\n'
        "</svg>\n"
    )

    with open(args.destination, "w", encoding="utf-8") as handle:
        handle.write(out)

    print(f"{args.source} -> {args.destination}")
    print(f"  mark spans {span}% of a 100-unit disc, viewBox {view_box}")

    worst = None
    for rgb in fills(inner):
        ratio = contrast_ratio(rgb, args.color)
        flag = "ok" if ratio >= 3.0 else "TOO LOW"
        print("  #%02x%02x%02x on %s = %.2f:1  (%s)" % (*rgb, disc, ratio, flag))
        worst = ratio if worst is None else min(worst, ratio)

    if worst is None:
        print("  no flat fills found -- check the result by eye.")
    elif worst < 3.0:
        sys.exit("  lowest contrast is under 3:1 -- use a deeper --color.")


if __name__ == "__main__":
    main()
